# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
    ]
